nodeLinker: node-modules
npmRegistryServer: "https://registry.npmjs.org/"
npmScopes:
  my:
    npmRegistryServer: "https://3447-2409-4090-2043-1c16-c457-863d-80c9-57a2.ngrok-free.app/repository/Ds-Monorepo/"
    auth:
      username: ${NEXUS_USER}
      password: ${NEXUS_PASSWORD_BASE64}

