name: Deploy Storybook

on:
  push:
    branches: ["master"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up .npmrc for Nexus Basic Auth
        run: |
          echo "registry=http://your-nexus-host:8081/repository/Ds-Monorepo/" > ~/.npmrc
          echo "//your-nexus-host:8081/repository/Ds-Monorepo/:username=admin" >> ~/.npmrc
          echo "//your-nexus-host:8081/repository/Ds-Monorepo/:_password=${{ secrets.NEXUS_PASSWORD_BASE64 }}" >> ~/.npmrc
          echo "//your-nexus-host:8081/repository/Ds-Monorepo/:email=subravjadhav@gmail.com" >> ~/.npmrc
          echo "//your-nexus-host:8081/repository/Ds-Monorepo/:always-auth=true" >> ~/.npmrc

      - name: Build and Publish @my/core to Nexus
        working-directory: packages/core
        run: |
          yarn install --frozen-lockfile
          yarn build
          npm publish --registry=http://your-nexus-host:8081/repository/Ds-Monorepo/

      - name: Build and Push Storybook Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/subrav2202/ds-monorepo:latest
          build-args: |
            NEXUS_USER=admin
            NEXUS_PASSWORD_BASE64=${{ secrets.NEXUS_PASSWORD_BASE64 }}
